# Generated by Django 4.2.7 on 2023-12-13 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_aitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.TextField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.url')),
            ],
            options={
                'unique_together': {('element', 'url')},
            },
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AlterUniqueTogether(
            name='aitem',
            unique_together={('element', 'url')},
        ),
    ]
